// <auto-generated />
namespace PeriodAid.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _04071739 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_04071739));
        
        string IMigrationMetadata.Id
        {
            get { return "201604070939157_04071739"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
