// <auto-generated />
namespace PeriodAid.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _03111457 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03111457));
        
        string IMigrationMetadata.Id
        {
            get { return "201603110958367_03111457"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
